### ISSUE TITLE
Error in cpp_linear(mt1 = x, mt2 = y, method = match(method, c("cosine", : std::bad_alloc

### ISSUE THREAD

**Issue by yiyelinfeng** [SydneyBioX/scClassify#3]
Hi, when I run this script : pred_res <- predict_scClassify(exprsMat_test = P115.combined[['RNA']]@data, trainRes = trainClass, algorithm = "WKNN", features = c("limma"), similarity = c("pearson", "spearman"), prob_threshold = 0.7, verbose = TRUE)
there is an error:
Performing unweighted ensemble learning... 
Using parameters: 
similarity  algorithm   features 
 "pearson"     "WKNN"    "limma" 
Error in cpp_linear(mt1 = x, mt2 = y, method = match(method, c("cosine",  : 
  std::bad_alloc

I want to know how to fix this.

Cheers,
Lin

**Comment by YingxinLin** [comment]
Hi Lin,

Thank you for your interest in scClassify. May I ask you about what is the size of your train data and test data, and are they as the sparse matrix class?

Thank you,
Yingxin
