### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by Acribbs** [SydneyBioX/scClassify#4]
I have tried downloading and installing the package without success. I have the following error.

The strange thing is that it is trying to find macosx el-capitan can packages, while I am running Mojave

Any suggestions?
thanks. 
```
devtools::install_github("SydneyBioX/scClassify")
Downloading GitHub repo SydneyBioX/scClassify@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                             
2: CRAN packages only              
3: None                            
4: igraph (1.2.4.2 -> 1.2.5) [CRAN]
5: dplyr  (0.8.4   -> 0.8.5) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
3
Installing 13 packages: ggraph, minpack.lm, mixtools, pbmcapply, proxy, proxyC, diptest, tweenr, polyclip, ggforce, tidygraph, graphlayouts, segmented
Error: Failed to install 'scClassify' from GitHub:
  (converted from warning) unable to access index for repository https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6:
  cannot open URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/PACKAGES'
```

**Comment by YingxinLin** [comment]
Hi,

It seems like Rstudio is not able to access those links. I am not sure if these two links would help: 
https://community.rstudio.com/t/install-packages-unable-to-access-index-for-repository-try-disabling-secure-download-method-for-http/16578.
https://community.rstudio.com/t/unable-to-install-package-in-r-studio/15930

You could try to install these packages: ggraph, minpack.lm, mixtools, pbmcapply, proxy, proxyC, diptest, tweenr, polyclip, ggforce, tidygraph, graphlayouts, segmented first, and then download the package from the GitHub and install it locally.

Hope the above helps.

Yingxin

**Comment by Acribbs** [comment]
Perfect! Thanks all installed
