### ISSUE TITLE
predict_scClassifyJoint and multiple similarity metrics

### ISSUE THREAD

**Issue by annajbott** [SydneyBioX/scClassify#6]
Hi,
Great tool! scClassify seems to be working well for most of my use cases. 
I've been using your PBMC joint model (http://www.maths.usyd.edu.au/u/yingxinl/wwwnb/scClassify/jointPBMCClass.rds).
I used the first model within this list and that worked fine with `predict_scClassify` with two similarity measures ( `c("pearson", "spearman")`). However when I tried to use the whole scClassifyTrainModelList with `predict_scClassifyJoint` it did not work with two+ similarity measures, as the variable `ensemble` was set to true and failed here: (https://github.com/SydneyBioX/scClassify/blob/master/R/predict_scClassify.R#L218 ; https://github.com/SydneyBioX/scClassify/blob/master/R/ensemble.R#L91)  

What I've been running (where `similarity` is a vector containing measures to use e.g. c("pearson", "spearman")):
```
pred_res <- predict_scClassifyJoint(exprsMat_test = dgc_mat,
                                 trainRes = trainClass, # or pre-made reference using
                                 cellTypes_test = NULL,
                                 algorithm = "WKNN",
                                 features = c("limma"),
                                 similarity = similarity,
                                 prob_threshold = 0.7,
                                 verbose = FALSE)
```
The error message:

```
Error in vapply(seq_len(length(resType)), function(i) { :  \
                                               values must be length 2, \
                                              but FUN(X[[1]]) result is length 60 \
                                             Calls: predict_scClassifyJoint ... calEnsembleRes -> apply -> FUN -> getResByWeights -> vapply
```

I ran this again using a single similarity measure, `similarity = "pearson"` and it worked fine. So just seems to be an issue with predict_scClassifyJoint and using multiple similarity calculation methods. 

Thanks!

Best wishes,
Anna

**Comment by YingxinLin** [comment]
Dear Anna,

Thank you very much for trying out our tool! I have an update few weeks ago to fix a related error, and I am wondering if the current GitHub version of the package would solve the issues. Please let me know how it goes.

Best wishes,
Yingxin
