### ISSUE TITLE
cellTypes_test missing default in predict_scClassifyJoint

### ISSUE THREAD

**Issue by lazappi** [SydneyBioX/scClassify#7]
This throws an error if `cellTypes_test` is not set (despite the documentation saying it is optional).

https://github.com/SydneyBioX/scClassify/blob/64fb85313b3ff0f2464fbb287ba3e7a0538d0228/R/predict_scClassify.R#L283-L287

Should probably be set to `NULL` to match `predict_scClassifyJoint()`

**Comment by YingxinLin** [comment]
Thank you for picking this up! Just fix this in the latest commit.
